#include <stdio.h>

int main(void)
{
  printf("# generated by vectors.c - do not edit\n");
  printf("# handlers\n");
  printf(".globl alltraps\n");

  for (int i = 0; i < 256; i++)
  {
    printf(".globl vector%d\n", i);
    printf("vector%d:\n", i);

    if (!(i == 8 || (i >= 10 && i <= 14) || i == 17))
    {
      printf("  pushl $0\n");
    }
    printf("  pushl $%d\n", i);
    printf("  jmp alltraps\n");
  }

  printf("\n# vector table\n");
  printf(".data\n");
  printf(".globl vectors\n");
  printf("vectors:\n");

  for (int i = 0; i < 256; i++)
  {
    printf("  .long vector%d\n", i);
  }

  return 0;
}
